// Code generated by Boiler; DO NOT EDIT.

package config

import (
  "context"

  "github.com/ushakovn/boiler/pkg/config"
  "github.com/ushakovn/boiler/pkg/config/types"
)

const (
  // Токен доступа для GitHub
  GithubAuthToken configKey = "github_auth_token"
)

// configKey strict type for config key
type configKey string

// Get value of the specified key
func Get(ctx context.Context, key configKey) types.Value {
  return config.ContextClient(ctx).GetValue(ctx, string(key))
}

// Watch watches changes to the value of the specified key
func Watch(ctx context.Context, key configKey, action func(value types.Value)) {
  config.ContextClient(ctx).WatchValue(ctx, string(key), action)
}
